### ISSUE TITLE
Consider to check the output fqi file size for faulty / abusive indexer behaviour

### ISSUE THREAD

**Issue by dankwart-de** [DKFZ-ODCF/FastqIndEx#19]
If the file grows too large (half the size of the FASTQ?), the indexer should stop and report this.

**Comment by vinjana** [comment]
1. Why should that happen?
2. Should that only be done for large FASTQs? For small FASTQs it doesn't really matter.

**Comment by dankwart-de** [comment]
1. It is not the matter of why. It just happened and the index file was nearly 40 times the size of the FASTQ (when I aborted! It would've grown even larger). It is obviously a bug, so this mechanism is more a failsafe to prevent the indexer from causing mayhem and destruction. The dataset was a small one from the ncbi site.
2. As said, it should be more a general failsafe.

**Comment by dankwart-de** [comment]
Even with a lot of small concatenated files and small index distance settings, the fqi files should not grow larger than maybe half of the initial FASTQ size. I think it is safe to stop then.

**Comment by vinjana** [comment]
O.k., a bug. Probably I was too quick in the response and didn't see that this is labelled as bug. Better remove the enhancement label.

**Comment by dankwart-de** [comment]
Test files were downloaded from here:
https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?exp=SRX000001&cmd=search&m=downloads&s=seq

What I found out is, that the checked files contain very small compressed blocks each holding just a few bytes. To encounter this, I think of some sort of failsafe distance when writing index entries. So not only the block distance would be looked at but also the Byte distance to the last written index entry.

In one exemplary case, the file size is approximately 145MB and it contains around 7,35 million compressed blocks. This results in ca. 20Bytes per block.

**Comment by dankwart-de** [comment]
Interesting fact for the mentioned file:
Recompressed with gzip default settings, it consists of ~1800 compressed blocks.

**Comment by dankwart-de** [comment]
Ok, with the new storage strategies, this issue is not relevant anymore.
