### ISSUE TITLE
Extend CLI interface

### ISSUE THREAD

**Issue by dankwart-de** [DKFZ-ODCF/FastqIndEx#5]
The current implementation is not very nice, we might also need to use something else than the Boost CLI library. Also some things are missing.

What I had in mind is:
``` Bash
# Index taking:
# - The mandatory positional compressed FASTQ file argument (or - for stdin)
# - The optional positional indexfile argument
# - The optional blockinterval (Store only every nth IndexEntry)
fastqindex index ( - | (FASTQ)file ) [indexfile] [--blockinterval 1..n]

# Extract taking:
# - The mandatory positional compressed FASTQ file argument
# - The optional positional indexfile argument 
# - The mandatory positional output FASTQ file argument (or - for stdout)
# - The optional extractionmultiplier argument which defaults to 4 for FASTQ files
#   The tool can also be used for regular text files
# - The optional disablefastqchecks argument, which will (in the future) disable further checks for FASTQ consistency
fastqindex extract (FASTQ)file [indexfile] ( - | (FASTQ)file) [--extractionmultiplier 1..n]  [--disablefastqchecks]
```

**Comment by vinjana** [comment]
1. I see very often, that file parameters are given behind options. That is

fastqindex index --blockinterval ... ( - | FASTQ ) [indexfile]

2. I still dislike all-minuscules. So I'd prefer:

fastqindex index --blockInterval ...  ( - | FASTQ ) [indexfile]

The same for "extract".

**Comment by vinjana** [comment]
Another common interface is to have all parameters as options.

-m $mode -i $inFastq -o $outIndex

But still the previous suggestion

fastqindex index --blockInterval ... ( - | FASTQ ) [indexfile]

has the advantage of being similar to samtools.

**Comment by dankwart-de** [comment]
Should be fine for now. Made it look a bit like the samtools CLI interface. Currently use TCLAP for it.
